import type { CanonicalEffect } from './types';
import { EXTRA_LIBRARY } from './catalog-extra';
import { nleRecipes, transformRecipes } from './recipes';

function fx(
  partial: Omit<CanonicalEffect, 'minVisualClues' | 'combinations'> & {
    minVisualClues?: number;
    combinations?: string[];
  }
): CanonicalEffect {
  return {
    minVisualClues: 3,
    combinations: [],
    ...partial,
  };
}

const blurAE = (name: string) =>
  nleRecipes({
    ae: {
      name,
      steps: [
        `Effect > Blur & Sharpen > ${name}`,
        'Match angle / center to the camera move',
        'Increase blur length during fast movement',
      ],
      map: { Direction: 'Direction', 'Blur Length': 'Blur Length' },
    },
    premiere: {
      name,
      steps: [
        `Effects > Blur & Sharpen > ${name}`,
        'Set direction to the motion vector',
        'Keyframe length on the impact frames',
      ],
    },
    capcut: {
      name: 'Blur / Motion Blur',
      steps: [
        'Effects > Body / Blur',
        'Align blur direction with movement',
        'Raise strength on the fast frames',
      ],
    },
    davinci: {
      name: 'OpenFX Directional Blur',
      steps: [
        'Effects > Blur > Directional Blur',
        'Set angle to the move',
        'Keyframe length',
      ],
    },
    vn: {
      name: 'Blur',
      steps: ['Add Blur', 'Set direction', 'Keyframe intensity'],
    },
  });

const CORE_LIBRARY: CanonicalEffect[] = [
  fx({
    id: 'FX_000124',
    canonicalName: 'Directional Blur',
    type: 'effect',
    category: 'Blur',
    subcategory: 'Directional Blur',
    description: 'Streaks pixels along one axis to sell camera or subject speed.',
    visualSignatures: [
      'Image stretches in one direction',
      'Blur follows movement direction',
      'Strength increases during fast movement',
    ],
    detectionKeywords: ['directional blur', 'horizontal streak', 'smear', 'whip'],
    aliases: ['Motion blur', 'directional motion blur', 'speed smear'],
    parameters: [
      { name: 'Direction', range: '0°–360°' },
      { name: 'Blur Length', range: '0–100' },
    ],
    layerOrder: 'Above base footage, below overlays',
    similarEffects: ['Motion Blur', 'Radial Blur', 'Zoom Blur'],
    softwareRecipes: blurAE('Directional Blur'),
  }),
  fx({
    id: 'FX_000125',
    canonicalName: 'Gaussian Blur',
    type: 'effect',
    category: 'Blur',
    subcategory: 'Gaussian Blur',
    description: 'Even defocus used for background melt or transition holds.',
    visualSignatures: ['Soft even haze', 'Edges lose contrast', 'No directional streak'],
    detectionKeywords: ['gaussian', 'soft blur', 'defocus'],
    aliases: ['Soft blur', 'defocus'],
    parameters: [{ name: 'Blurriness', range: '0–100' }],
    layerOrder: 'On adjustment layer or clip',
    similarEffects: ['Lens Blur', 'Fast Blur'],
    softwareRecipes: blurAE('Gaussian Blur'),
  }),
  fx({
    id: 'FX_000126',
    canonicalName: 'Radial Blur',
    type: 'effect',
    category: 'Blur',
    subcategory: 'Radial Blur',
    description: 'Spin or zoom blur radiating from a center point.',
    visualSignatures: ['Streaks from a center', 'Spin or zoom smear', 'Center stays sharper'],
    detectionKeywords: ['radial blur', 'spin blur', 'zoom blur'],
    aliases: ['Zoom blur', 'spin blur'],
    parameters: [
      { name: 'Amount', range: '0–100' },
      { name: 'Type', range: 'Spin / Zoom' },
    ],
    layerOrder: 'On clip during the move',
    similarEffects: ['Zoom Blur', 'Directional Blur'],
    softwareRecipes: blurAE('Radial Blur'),
  }),
  fx({
    id: 'FX_000130',
    canonicalName: 'Outer Glow',
    type: 'effect',
    category: 'Glow',
    subcategory: 'Glow',
    description: 'Soft bloom around highlights or text.',
    visualSignatures: ['Halo around highlights', 'Bloom on edges', 'Whites wrap outward'],
    detectionKeywords: ['glow', 'bloom', 'halo', 'outer glow'],
    aliases: ['Bloom', 'highlight glow'],
    parameters: [
      { name: 'Threshold', range: '0–1' },
      { name: 'Radius', range: '4–80' },
      { name: 'Brightness', range: '0–4' },
    ],
    layerOrder: 'On text or highlight layer',
    similarEffects: ['HDR Sharpen', 'Light Leak'],
    softwareRecipes: nleRecipes({
      ae: {
        name: 'Glow',
        steps: ['Effect > Stylize > Glow', 'Raise Threshold until only highlights bloom', 'Keyframe during the hit'],
      },
      premiere: {
        name: 'Glow',
        steps: ['Effects > Stylize > Glow', 'Limit to highlights', 'Keyframe intensity'],
      },
      capcut: {
        name: 'Glow',
        steps: ['Effects > Glow', 'Set intensity', 'Keyframe on the beat'],
      },
      davinci: {
        name: 'Glow',
        steps: ['OpenFX Glow', 'Restrict to highlights', 'Keyframe'],
      },
      vn: {
        name: 'Glow',
        steps: ['Add Glow', 'Raise intensity', 'Keyframe'],
      },
    }),
  }),
  fx({
    id: 'FX_000140',
    canonicalName: 'Unsharp Mask / HDR Sharpen',
    type: 'effect',
    category: 'Sharpen',
    subcategory: 'Sharpen',
    description: 'Micro-contrast pass that makes edges pop like HDR social grades.',
    visualSignatures: ['Crisp edges', 'Halo on contrast edges', 'Texture looks harder'],
    detectionKeywords: ['sharpen', 'hdr', 'crisp', 'unsharp'],
    aliases: ['HDR Sharpen', 'detail enhance'],
    parameters: [
      { name: 'Amount', range: '0–120' },
      { name: 'Radius', range: '0.5–4' },
    ],
    layerOrder: 'Late in the grade stack',
    similarEffects: ['Glow'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Unsharp Mask', steps: ['Effect > Blur & Sharpen > Sharpen', 'Keep radius small', 'Park on an adjustment'] },
      premiere: { name: 'Sharpen', steps: ['Effects > Sharpen', 'Keep it subtle', 'Mask faces if needed'] },
      capcut: { name: 'Sharpen', steps: ['Adjust > Sharpen', 'Raise slightly', 'Check skin'] },
      davinci: { name: 'Sharpen', steps: ['Color page > Sharpen', 'Midtone detail', 'Check 100%'] },
      vn: { name: 'Sharpen', steps: ['Enhance > Sharpen', 'Small amount'] },
    }),
  }),
  fx({
    id: 'FX_000150',
    canonicalName: 'RGB Split Glitch',
    type: 'effect',
    category: 'Distortion',
    subcategory: 'RGB Split',
    description: 'Chromatic offset of R/G/B channels, often on a cut.',
    visualSignatures: ['Red/cyan fringe', 'Channels slide apart', 'Usually brief'],
    detectionKeywords: ['rgb', 'chromatic', 'glitch', 'aberration'],
    aliases: ['Chromatic aberration', 'RGB shift'],
    parameters: [
      { name: 'Shift X', range: '0–40px' },
      { name: 'Shift Y', range: '0–40px' },
    ],
    layerOrder: 'On the outgoing or incoming shot',
    similarEffects: ['CRT Glitch', 'Scan Lines'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Shift Channels + Transform', steps: ['Duplicate layer 3 times', 'Isolate R/G/B', 'Offset X on the hit'] },
      premiere: { name: 'RGB Split', steps: ['Effects > Transform / RGB Split', 'Keyframe the offset', 'Return to 0'] },
      capcut: { name: 'RGB Split', steps: ['Effects > Glitch / RGB', 'Keyframe', 'Reset after the cut'] },
      davinci: { name: 'RGB Split', steps: ['OpenFX chromatic aberration', 'Keyframe', 'Reset'] },
      vn: { name: 'Glitch', steps: ['Add Glitch/RGB', 'Keyframe'] },
    }),
  }),
  fx({
    id: 'FX_000160',
    canonicalName: 'Film Grain',
    type: 'effect',
    category: 'Noise/Grain',
    subcategory: 'Grain',
    description: 'Fine grain overlay that sits on the whole frame.',
    visualSignatures: ['Fine noisy texture', 'Visible in flats', 'Constant or pulsed'],
    detectionKeywords: ['grain', 'noise', 'film grain', '32mm'],
    aliases: ['Noise', 'film texture'],
    parameters: [
      { name: 'Amount', range: '4–40' },
      { name: 'Size', range: '0.5–3' },
    ],
    layerOrder: 'Above grade, below text',
    similarEffects: ['Dust', 'VHS Overlay'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Add Grain', steps: ['Effect > Noise & Grain > Add Grain', 'Match 35mm/16mm', 'Set blending'] },
      premiere: { name: 'Noise', steps: ['Effects > Noise', 'Low amount', 'Clip layer'] },
      capcut: { name: 'Grain', steps: ['Effects > Texture / Grain', 'Set amount'] },
      davinci: { name: 'Film Grain', steps: ['Color > Film Grain', 'ISO-style amount'] },
      vn: { name: 'Grain', steps: ['Add Grain', 'Set amount'] },
    }),
  }),
  fx({
    id: 'FX_000170',
    canonicalName: 'Teal & Orange Grade',
    type: 'effect',
    category: 'Color',
    subcategory: 'Grade',
    description: 'Split-tone grade: cool shadows, warm highlights.',
    visualSignatures: ['Cyan/teal shadows', 'Warm skin highlights', 'Lifted contrast'],
    detectionKeywords: ['teal', 'orange', 'split tone', 'cinematic grade'],
    aliases: ['Cinematic grade', 'blockbuster look'],
    parameters: [
      { name: 'Contrast', range: '+4–+25%' },
      { name: 'Saturation', range: '80–120%' },
      { name: 'Temperature', range: 'warm highlights' },
    ],
    layerOrder: 'On the color/adjustment layer',
    similarEffects: ['HDR Sharpen', 'Film Grain'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Lumetri Color', steps: ['Lumetri > Curves / Color Wheels', 'Cool shadows, warm highs', 'Add contrast'] },
      premiere: { name: 'Lumetri Color', steps: ['Color Wheels', 'Teal shadows / orange mids', 'Contrast'] },
      capcut: { name: 'Filters + Adjust', steps: ['Filters > cinematic', 'Adjust > Contrast / Temp'] },
      davinci: { name: 'Color Wheels', steps: ['Lift teal', 'Gamma/Gain warm', 'Contrast'] },
      vn: { name: 'Filter + Adjust', steps: ['Cinematic filter', 'Contrast / Temperature'] },
    }),
  }),
  fx({
    id: 'FX_000180',
    canonicalName: 'Flash Frame',
    type: 'effect',
    category: 'Lighting',
    subcategory: 'Flash',
    description: '1–3 frame white or exposure burst on a cut or beat.',
    visualSignatures: ['Frame goes near-white', 'Very short', 'Often on a beat'],
    detectionKeywords: ['flash', 'white flash', 'exposure burst'],
    aliases: ['White flash', 'impact flash'],
    parameters: [
      { name: 'Peak Opacity', range: '40–100%' },
      { name: 'Duration', range: '1–4 frames' },
    ],
    layerOrder: 'Top of picture, below captions',
    similarEffects: ['Light Leak', 'Glow'],
    combinations: ['CMP_ZOOM_ROTATE_FLASH'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Solid + Opacity', steps: ['White solid', 'Opacity 0 → 80 → 0', '1–3 frames'] },
      premiere: { name: 'Dip to White', steps: ['Dip to White', 'Shorten to 2–4 frames'] },
      capcut: { name: 'Flash', steps: ['Effects > Flash', 'Short duration'] },
      davinci: { name: 'Flash / Adjustment', steps: ['Gain spike or Flash OFX', '1–3 frames'] },
      vn: { name: 'Flash', steps: ['Add Flash', 'Shorten'] },
    }),
  }),
  fx({
    id: 'FX_000181',
    canonicalName: 'Lens Flare',
    type: 'effect',
    category: 'Lighting',
    subcategory: 'Flare',
    description: 'Optical flare streak from a bright source.',
    visualSignatures: ['Anamorphic streak or orbs', 'Tied to a light', 'Moves with camera'],
    detectionKeywords: ['flare', 'anamorphic', 'lens flare'],
    aliases: ['Anamorphic flare'],
    parameters: [{ name: 'Intensity', range: '0–100' }],
    layerOrder: 'Above picture',
    similarEffects: ['Light Leak', 'Glow'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Optics Compensation / Flare', steps: ['Effect > Generate > Lens Flare', 'Track the source'] },
      premiere: { name: 'Lens Flare', steps: ['Effects > Lens Flare', 'Set source'] },
      capcut: { name: 'Flare', steps: ['Effects > Flare', 'Position'] },
      davinci: { name: 'Lens Flare', steps: ['OpenFX Flare', 'Track'] },
      vn: { name: 'Flare', steps: ['Add Flare'] },
    }),
  }),
  fx({
    id: 'FX_000190',
    canonicalName: 'Kinetic Text Pop',
    type: 'effect',
    category: 'Text',
    subcategory: 'Kinetic Text',
    description: 'Text that scales/snaps on with glow, often on a beat.',
    visualSignatures: ['Text appears suddenly', 'Scale overshoot', 'Often glowing'],
    detectionKeywords: ['text pop', 'kinetic', 'caption slam', 'title'],
    aliases: ['Text slam', 'caption pop'],
    parameters: [
      { name: 'Scale', range: '80% → 108%' },
      { name: 'Duration', range: '0.12–0.4s' },
    ],
    layerOrder: 'Top of stack',
    similarEffects: ['Outer Glow', 'Impact Shake'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Text + Scale', steps: ['New Text', 'Scale + Opacity keyframes', 'Glow'] },
      premiere: { name: 'Essential Graphics', steps: ['Text layer', 'Scale keyframes'] },
      capcut: { name: 'Text + Animation', steps: ['Add text', 'In animation + keyframes'] },
      davinci: { name: 'Text+', steps: ['Text+', 'Transform keyframes'] },
      vn: { name: 'Text', steps: ['Add text', 'Keyframe scale'] },
    }),
  }),
  fx({
    id: 'FX_000200',
    canonicalName: 'Particle Burst',
    type: 'effect',
    category: 'Particle',
    subcategory: 'Particle',
    description: 'Sparks, dust, or debris emitted on an impact.',
    visualSignatures: ['Many small elements emit', 'Tied to an impact', 'Fades quickly'],
    detectionKeywords: ['particle', 'spark', 'debris', 'dust burst'],
    aliases: ['Spark burst', 'impact particles'],
    parameters: [{ name: 'Birth Rate', range: 'low–high' }],
    layerOrder: 'Above footage',
    similarEffects: ['Speed Lines', 'Dust'],
    softwareRecipes: nleRecipes({
      ae: { name: 'CC Particle World', steps: ['CC Particle World', 'Burst on the hit'] },
      premiere: { name: 'Particle overlay', steps: ['Overlay a particle clip', 'Screen / Add'] },
      capcut: { name: 'Particles', steps: ['Effects > Particles', 'Time to the beat'] },
      davinci: { name: 'Particle OFX', steps: ['Fusion particles or overlay'] },
      vn: { name: 'Particles', steps: ['Add particle sticker'] },
    }),
  }),
  fx({
    id: 'FX_000210',
    canonicalName: 'VHS / CRT Overlay',
    type: 'effect',
    category: 'Screen',
    subcategory: 'Scanline',
    description: 'Analog TV look: scan lines, tracking, mild RGB.',
    visualSignatures: ['Horizontal scan lines', 'Soft tracking warp', 'Slight RGB'],
    detectionKeywords: ['vhs', 'crt', 'scanline', 'tv look'],
    aliases: ['CRT overlay', 'TV lines'],
    parameters: [{ name: 'Line Opacity', range: '20–80%' }],
    layerOrder: 'Above grade, below text',
    similarEffects: ['Scan Lines', 'RGB Split'],
    softwareRecipes: nleRecipes({
      ae: { name: 'CC Lines + Grain', steps: ['Scanline overlay', 'Blend Overlay/Multiply', 'Opacity ~65%'] },
      premiere: { name: 'VHS overlay', steps: ['Overlay clip', 'Blend + opacity'] },
      capcut: { name: 'VHS', steps: ['Effects > VHS / Retro'] },
      davinci: { name: 'VHS overlay', steps: ['Overlay in Edit', 'Composite mode'] },
      vn: { name: 'VHS', steps: ['Add VHS filter'] },
    }),
  }),
  fx({
    id: 'OV_000301',
    canonicalName: 'Horizontal Scan Line / Black Bar Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Scanline',
    description: 'Repeated horizontal dark lines across the 9:16 frame.',
    visualSignatures: [
      'Repeated horizontal dark lines',
      'Lines sit above the picture',
      'Does not distort the subject, only darkens bands',
    ],
    detectionKeywords: ['scan line', 'black bar', 'scanline', 'tv bars', 'horizontal lines'],
    aliases: ['Black line effect', 'TV scan bars', 'horizontal bars'],
    parameters: [
      { name: 'Opacity', range: '30–80%' },
      { name: 'Blend Mode', range: 'Multiply / Overlay / Analyze' },
    ],
    layerOrder: 'Above base footage, below text',
    similarEffects: ['Letterbox', 'CRT Lines', 'Grid Overlay'],
    softwareRecipes: nleRecipes({
      ae: {
        name: 'Scanline PNG / CC RepeTile',
        steps: [
          'Import horizontal line overlay',
          'Scale to full 9:16',
          'Set opacity ~65% and Multiply/Overlay',
        ],
      },
      premiere: {
        name: 'Scanline overlay',
        steps: ['Place overlay on V2', 'Opacity ~65%', 'Blend Multiply'],
      },
      capcut: {
        name: 'Overlay',
        steps: ['Overlay > scan line / line texture', 'Opacity 65%', 'Full frame'],
      },
      davinci: {
        name: 'Overlay still',
        steps: ['Edit overlay', 'Composite Multiply', 'Opacity 0.65'],
      },
      vn: {
        name: 'Overlay',
        steps: ['Add overlay', 'Opacity 65%'],
      },
    }),
  }),
  fx({
    id: 'OV_000302',
    canonicalName: 'Letterbox / Black Bars',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Letterbox',
    description: 'Cinematic black mattes on the long edges of the frame.',
    visualSignatures: ['Solid black bands', 'Symmetrical', 'Does not move with the subject'],
    detectionKeywords: ['letterbox', 'black bars', 'cinematic bars', 'matte'],
    aliases: ['Film matte', 'cinematic bars', '21:9 bars'],
    parameters: [{ name: 'Bar Height', range: '4–18%' }],
    layerOrder: 'Above picture, below text',
    similarEffects: ['Frame Overlay', 'Scan Lines'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Shape layers', steps: ['Two black solids', 'Pin top/bottom', 'Parent to frame'] },
      premiere: { name: 'Crop / Mattes', steps: ['Crop or graphic bars', 'Lock to frame'] },
      capcut: { name: 'Ratio / Overlay', steps: ['Canvas or overlay bars'] },
      davinci: { name: 'Blanking', steps: ['Inspector blanking or Fusion bars'] },
      vn: { name: 'Ratio', steps: ['Add black bars overlay'] },
    }),
  }),
  fx({
    id: 'OV_000303',
    canonicalName: 'Light Leak',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Light Leak',
    description: 'Warm analog leak wiping across the frame.',
    visualSignatures: ['Orange/amber wash', 'Moves across frame', 'Soft edges'],
    detectionKeywords: ['light leak', 'film burn', 'analog leak'],
    aliases: ['Film burn', 'analog leak'],
    parameters: [{ name: 'Opacity', range: '20–80%' }],
    layerOrder: 'Add / Screen above picture',
    similarEffects: ['Lens Flare', 'Flash Frame'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Light leak footage', steps: ['Screen blend', 'Time to the cut'] },
      premiere: { name: 'Light leak', steps: ['Overlay clip', 'Blend Screen'] },
      capcut: { name: 'Light leak', steps: ['Effects > Light leak'] },
      davinci: { name: 'Light leak', steps: ['Composite Add/Screen'] },
      vn: { name: 'Light leak', steps: ['Add overlay'] },
    }),
  }),
  fx({
    id: 'OV_000304',
    canonicalName: 'Dust & Scratches',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Grain',
    description: 'Occasional specks and hairline scratches.',
    visualSignatures: ['Tiny white/black specks', 'Vertical hairs', 'Random'],
    detectionKeywords: ['dust', 'scratches', 'film damage'],
    aliases: ['Film damage'],
    parameters: [{ name: 'Amount', range: 'low–medium' }],
    layerOrder: 'Above grain',
    similarEffects: ['Film Grain'],
    softwareRecipes: nleRecipes({
      ae: { name: 'CC Wide Time / overlay', steps: ['Dust overlay', 'Screen + low opacity'] },
      premiere: { name: 'Dust overlay', steps: ['Overlay', 'Blend'] },
      capcut: { name: 'Dust', steps: ['Effects > Dust'] },
      davinci: { name: 'Dirt overlay', steps: ['Composite'] },
      vn: { name: 'Dust', steps: ['Overlay'] },
    }),
  }),
  fx({
    id: 'OV_000305',
    canonicalName: 'Speed Lines',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Particle',
    description: 'Manga-style lines radiating or streaming to sell speed.',
    visualSignatures: ['Radial or trailing lines', 'High contrast', 'During motion'],
    detectionKeywords: ['speed lines', 'manga lines', 'action lines'],
    aliases: ['Action lines'],
    parameters: [{ name: 'Opacity', range: '30–90%' }],
    layerOrder: 'Above picture',
    similarEffects: ['Zoom Blur', 'Particle Burst'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Speed line overlay', steps: ['Overlay PNG/loop', 'Screen'] },
      premiere: { name: 'Speed lines', steps: ['Overlay'] },
      capcut: { name: 'Speed line', steps: ['Effects > Speed line'] },
      davinci: { name: 'Overlay', steps: ['Composite'] },
      vn: { name: 'Speed line', steps: ['Sticker/overlay'] },
    }),
  }),
  fx({
    id: 'MOTION_001',
    canonicalName: 'Zoom In + Clockwise Rotation',
    type: 'transform',
    category: 'Transform',
    subcategory: 'Zoom',
    description: 'Scale punch with positive Z rotation — never a bare “Zoom”.',
    visualSignatures: [
      'Frame enlarges around a subject',
      'Whole frame rotates a few degrees',
      'Often with motion blur',
    ],
    detectionKeywords: ['zoom in', 'punch in', 'scale', 'clockwise', 'rotation'],
    aliases: ['Punch-in', 'scale + rotate', 'zoom rotate'],
    parameters: [
      { name: 'Scale', range: '100% → 112–145%' },
      { name: 'Rotation', range: '0° → 6–15°' },
      { name: 'Position', range: 'optional X/Y offset' },
      { name: 'Duration', range: '0.25–0.6s' },
      { name: 'Easing', range: 'Ease Out + Overshoot' },
      { name: 'Motion Blur', range: 'On' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom Out', 'Impact Shake'],
    combinations: ['CMP_ZOOM_BLUR', 'CMP_ZOOM_ROTATE_FLASH'],
    softwareRecipes: transformRecipes('Scale + Rotation', 'Scale + Rotation', 'Zoom + Angle'),
  }),
  fx({
    id: 'MOTION_002',
    canonicalName: 'Zoom Out / Pull Back',
    type: 'transform',
    category: 'Transform',
    subcategory: 'Zoom',
    description: 'Scale comes down, revealing more of the frame.',
    visualSignatures: ['Frame recedes', 'Subject shrinks', 'Often eases out'],
    detectionKeywords: ['zoom out', 'pull back', 'pull out'],
    aliases: ['Pull back', 'scale down'],
    parameters: [
      { name: 'Scale', range: '128% → 100%' },
      { name: 'Duration', range: '0.3–0.8s' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom In + Clockwise Rotation'],
    softwareRecipes: transformRecipes('Scale', 'Scale', 'Zoom'),
  }),
  fx({
    id: 'MOTION_003',
    canonicalName: 'Impact Camera Shake',
    type: 'transform',
    category: 'Camera',
    subcategory: 'Shake',
    description: 'Short positional jitter on a hit.',
    visualSignatures: ['Frame hops a few pixels', '1–6 frames', 'On a transient'],
    detectionKeywords: ['shake', 'jitter', 'handheld', 'impact'],
    aliases: ['Handheld jitter', 'hit shake'],
    parameters: [
      { name: 'Amplitude', range: '4–24px' },
      { name: 'Duration', range: '0.08–0.25s' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom In + Clockwise Rotation'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Position wiggle / keyframes', steps: ['Keyframe Position', '2–4 hits', 'Motion Blur on'] },
      premiere: { name: 'Position', steps: ['Motion > Position', 'Small offsets'] },
      capcut: { name: 'Shake', steps: ['Effects > Shake', 'Short'] },
      davinci: { name: 'Position', steps: ['Inspector position keyframes'] },
      vn: { name: 'Shake', steps: ['Shake effect or position keys'] },
    }),
  }),
  fx({
    id: 'MOTION_004',
    canonicalName: 'Z-Axis Barrel Roll',
    type: 'transform',
    category: 'Camera',
    subcategory: 'Rotate',
    description: 'Large Z rotation, often 90–360°.',
    visualSignatures: ['Horizon tilts hard', 'Full or half spin', 'Usually blurred'],
    detectionKeywords: ['barrel', '360', 'roll', 'spin'],
    aliases: ['360 spin', 'barrel roll'],
    parameters: [
      { name: 'Rotation', range: '90–360°' },
      { name: 'Blur', range: 'on at mid-spin' },
    ],
    layerOrder: 'Transform + directional blur',
    similarEffects: ['Spin Transition'],
    softwareRecipes: transformRecipes('Rotation', 'Rotation', 'Angle'),
  }),
  fx({
    id: 'TR_000401',
    canonicalName: 'Whip Pan Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Whip Pan',
    description: 'Lateral smear that hides a cut.',
    visualSignatures: ['Horizontal smear', 'Cut in the blur', 'Direction continues'],
    detectionKeywords: ['whip pan', 'whip', 'swish pan'],
    aliases: ['Swish pan', 'blur pan'],
    parameters: [
      { name: 'Direction', range: '0° or 180° typically' },
      { name: 'Duration', range: '0.12–0.35s' },
    ],
    layerOrder: 'Across the cut',
    similarEffects: ['Directional Blur', 'Zoom Blur Transition'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Directional Blur + Cut', steps: ['Blur both sides of the cut', 'Cut at peak blur', 'Match direction'] },
      premiere: { name: 'Directional Blur', steps: ['Blur on A and B', 'Cut mid-smear'] },
      capcut: { name: 'Whip / Slide', steps: ['Transition > Whip or Slide', 'Add blur'] },
      davinci: { name: 'Directional Blur', steps: ['OFX blur both clips'] },
      vn: { name: 'Swipe', steps: ['Swipe transition + blur'] },
    }),
  }),
  fx({
    id: 'TR_000402',
    canonicalName: 'Zoom Blur Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Zoom',
    description: 'Radial zoom smear through a cut.',
    visualSignatures: ['Radial streaks', 'Cut at peak zoom blur', 'Center holds'],
    detectionKeywords: ['zoom blur transition', 'radial push', 'zoom through'],
    aliases: ['Radial push', 'zoom through'],
    parameters: [{ name: 'Amount', range: '20–80' }],
    layerOrder: 'Across the cut',
    similarEffects: ['Radial Blur', 'Whip Pan Transition'],
    softwareRecipes: blurAE('Radial Blur'),
  }),
  fx({
    id: 'TR_000403',
    canonicalName: 'Flash Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Flash',
    description: 'White flash that conceals the cut.',
    visualSignatures: ['Peak white at the cut', 'Symmetric fade', 'Short'],
    detectionKeywords: ['flash cut', 'dip to white', 'white transition'],
    aliases: ['Dip to white', 'impact flash cut'],
    parameters: [{ name: 'Peak', range: '60–100%' }],
    layerOrder: 'Across the cut',
    similarEffects: ['Flash Frame'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Dip to White', steps: ['White solid over the cut', 'Opacity peak at the edit'] },
      premiere: { name: 'Dip to White', steps: ['Apply Dip to White', 'Shorten'] },
      capcut: { name: 'Flash', steps: ['Transition > Flash'] },
      davinci: { name: 'Dip to Color', steps: ['Dip to white'] },
      vn: { name: 'Flash', steps: ['Flash transition'] },
    }),
  }),
  fx({
    id: 'TR_000404',
    canonicalName: 'Match Cut on Action',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Match Cut',
    description: 'Hard cut that continues motion or shape across shots.',
    visualSignatures: ['Action continues', 'Similar shape/direction', 'No dissolve'],
    detectionKeywords: ['match cut', 'match on action'],
    aliases: ['Action match', 'shape match'],
    parameters: [{ name: 'Offset', range: '±2 frames' }],
    layerOrder: 'Hard cut',
    similarEffects: ['Hard Cut'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Razor cut', steps: ['Cut on the action peak', 'Nudge ±1 frame'] },
      premiere: { name: 'Razor', steps: ['Cut on action'] },
      capcut: { name: 'Split', steps: ['Split on the move'] },
      davinci: { name: 'Blade', steps: ['Blade on action'] },
      vn: { name: 'Split', steps: ['Split on action'] },
    }),
  }),
  fx({
    id: 'TR_000405',
    canonicalName: 'Glitch Tear Cut',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Glitch',
    description: 'Digital tear / block displace into the next shot.',
    visualSignatures: ['Blocks or tears', 'RGB on the seam', 'Short'],
    detectionKeywords: ['glitch cut', 'tear', 'block glitch'],
    aliases: ['Digital tear', 'block displace'],
    parameters: [{ name: 'Displace', range: '4–40px' }],
    layerOrder: 'Across the cut',
    similarEffects: ['RGB Split Glitch'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Turbulent Displace + RGB', steps: ['Displace on the outgoing', 'Cut', 'RGB on incoming'] },
      premiere: { name: 'Glitch', steps: ['Glitch transition'] },
      capcut: { name: 'Glitch', steps: ['Transition > Glitch'] },
      davinci: { name: 'Glitch', steps: ['OFX glitch'] },
      vn: { name: 'Glitch', steps: ['Glitch transition'] },
    }),
  }),
  fx({
    id: 'TR_000406',
    canonicalName: 'Spin Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Spin',
    description: 'Rotation through the cut, often with blur.',
    visualSignatures: ['Spin continues across the cut', 'Blur at 90–180°', 'Settles on incoming'],
    detectionKeywords: ['spin transition', 'rotate transition'],
    aliases: ['Rotate transition'],
    parameters: [{ name: 'Rotation', range: '90–360°' }],
    layerOrder: 'Across the cut',
    similarEffects: ['Z-Axis Barrel Roll'],
    softwareRecipes: transformRecipes('Rotation', 'Rotation', 'Angle'),
  }),
  fx({
    id: 'TR_000407',
    canonicalName: 'Shake Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Shake',
    description: 'Impact shake that lands on the incoming shot.',
    visualSignatures: ['Shake peaks at the cut', 'Incoming settles'],
    detectionKeywords: ['shake transition', 'impact cut'],
    aliases: ['Hit cut'],
    parameters: [{ name: 'Amplitude', range: '8–30px' }],
    layerOrder: 'Across the cut',
    similarEffects: ['Impact Camera Shake'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Position', steps: ['Shake both sides of the cut'] },
      premiere: { name: 'Position', steps: ['Motion shake'] },
      capcut: { name: 'Shake', steps: ['Shake transition'] },
      davinci: { name: 'Position', steps: ['Keyframe shake'] },
      vn: { name: 'Shake', steps: ['Shake'] },
    }),
  }),
  fx({
    id: 'TR_000408',
    canonicalName: 'Hard Cut',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Match Cut',
    description: 'Instant shot change with no dissolve.',
    visualSignatures: ['Instant image change', 'No smear', 'Often on a beat'],
    detectionKeywords: ['hard cut', 'jump cut', 'straight cut'],
    aliases: ['Straight cut', 'jump cut'],
    parameters: [{ name: 'Offset', range: '0 frames' }],
    layerOrder: 'Edit point',
    similarEffects: ['Match Cut on Action'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Razor', steps: ['Cut', 'No crossfade'] },
      premiere: { name: 'Razor', steps: ['Cut'] },
      capcut: { name: 'Split', steps: ['Split'] },
      davinci: { name: 'Blade', steps: ['Blade'] },
      vn: { name: 'Split', steps: ['Split'] },
    }),
  }),
  fx({
    id: 'TR_000409',
    canonicalName: 'Dip to Black',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Flash',
    description: 'Luma fade to black, often an ending.',
    visualSignatures: ['Picture darkens to black', 'No white flash'],
    detectionKeywords: ['dip to black', 'fade to black', 'fade out'],
    aliases: ['Fade to black'],
    parameters: [{ name: 'Duration', range: '0.3–1.2s' }],
    layerOrder: 'End of sequence',
    similarEffects: ['Flash Transition'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Opacity', steps: ['Opacity to 0 or black solid'] },
      premiere: { name: 'Dip to Black', steps: ['Dip to Black'] },
      capcut: { name: 'Fade', steps: ['Fade to black'] },
      davinci: { name: 'Dip to Black', steps: ['Dip to black'] },
      vn: { name: 'Fade', steps: ['Fade out'] },
    }),
  }),
  fx({
    id: 'TR_000410',
    canonicalName: 'Masked Wipe Reveal',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Mask',
    description: 'Incoming shot revealed by a mask or object.',
    visualSignatures: ['Hard or feathered reveal edge', 'Shape travels', 'Incoming underneath'],
    detectionKeywords: ['wipe', 'mask reveal', 'object wipe'],
    aliases: ['Object transition', 'shape wipe'],
    parameters: [{ name: 'Feather', range: '0–40px' }],
    layerOrder: 'Track matte / mask',
    similarEffects: ['Whip Pan Transition'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Track Matte / Mask', steps: ['Animate mask path', 'Feather if needed'] },
      premiere: { name: 'Wipe', steps: ['Video Transitions > Wipe'] },
      capcut: { name: 'Wipe / Mask', steps: ['Mask or wipe transition'] },
      davinci: { name: 'Wipe / Fusion mask', steps: ['Wipe or Fusion'] },
      vn: { name: 'Wipe', steps: ['Wipe transition'] },
    }),
  }),
  fx({
    id: 'CMP_ZOOM_BLUR',
    canonicalName: 'Zoom + Directional Blur',
    type: 'compound',
    category: 'Transform',
    subcategory: 'Compound',
    description: 'Scale punch with directional smear — not a single “zoom effect”.',
    visualSignatures: ['Scale up', 'Streak in one direction', 'Blur peaks mid-move'],
    detectionKeywords: ['zoom blur', 'zoom + blur', 'punch smear'],
    aliases: ['Zoom smear', 'punch blur'],
    parameters: [
      { name: 'Scale', range: '100% → 128–145%' },
      { name: 'Blur Length', range: '0 → 20–50' },
      { name: 'Duration', range: '0.28–0.5s' },
    ],
    layerOrder: 'Transform then blur on the same clip',
    similarEffects: ['Zoom In + Clockwise Rotation', 'Directional Blur'],
    combinations: ['MOTION_001', 'FX_000124'],
    softwareRecipes: nleRecipes({
      ae: {
        name: 'Scale + Directional Blur',
        steps: ['Keyframe Scale', 'Add Directional Blur', 'Peak blur at fastest scale'],
      },
      premiere: {
        name: 'Scale + Directional Blur',
        steps: ['Motion Scale', 'Directional Blur', 'Keyframe both'],
      },
      capcut: {
        name: 'Keyframe Scale + Blur',
        steps: ['Scale keyframes', 'Motion blur / blur effect'],
      },
      davinci: {
        name: 'Zoom + Directional Blur',
        steps: ['Inspector zoom', 'Directional Blur OFX'],
      },
      vn: {
        name: 'Scale + Blur',
        steps: ['Scale keys', 'Blur'],
      },
    }),
  }),
  fx({
    id: 'CMP_ZOOM_ROTATE_FLASH',
    canonicalName: 'Zoom + Rotation + Motion Blur + Flash',
    type: 'compound',
    category: 'Transform',
    subcategory: 'Compound',
    description: 'Full impact recipe: scale, rotate, smear, and a flash peak.',
    visualSignatures: [
      'Scale increases',
      'Frame rotates',
      'Directional smear',
      'White flash on the beat',
    ],
    detectionKeywords: ['zoom rotate flash', 'impact combo', 'compound zoom'],
    aliases: ['Impact stack', 'zoom rotate flash'],
    parameters: [
      { name: 'Scale', range: '100% → 145%' },
      { name: 'Rotation', range: '0° → -8° to +12°' },
      { name: 'Directional Blur', range: '0 → 42' },
      { name: 'Flash', range: '0% → 70% → 0%' },
      { name: 'Duration', range: '0.32–0.45s' },
    ],
    layerOrder: 'Transform → blur → flash overlay',
    similarEffects: ['Zoom In + Clockwise Rotation', 'Flash Frame'],
    combinations: ['MOTION_001', 'FX_000124', 'FX_000180'],
    softwareRecipes: nleRecipes({
      ae: {
        name: 'Scale + Rotation + Directional Blur + Flash',
        steps: [
          'Keyframe Scale and Rotation',
          'Directional Blur length on the fastest frames',
          'White flash 0–70–0 on the beat',
        ],
      },
      premiere: {
        name: 'Motion + Blur + Dip to White',
        steps: ['Scale + Rotation', 'Directional Blur', 'Short white flash'],
      },
      capcut: {
        name: 'Keyframes + Blur + Flash',
        steps: ['Scale + Rotate keys', 'Blur', 'Flash'],
      },
      davinci: {
        name: 'Zoom + Angle + Blur + Flash',
        steps: ['Zoom + Angle', 'Directional Blur', 'Flash'],
      },
      vn: {
        name: 'Scale + Rotate + Flash',
        steps: ['Keyframes', 'Blur', 'Flash'],
      },
    }),
  }),
];

export const EFFECT_LIBRARY: CanonicalEffect[] = [...CORE_LIBRARY, ...EXTRA_LIBRARY];

export function libraryById(id: string): CanonicalEffect | undefined {
  return EFFECT_LIBRARY.find((e) => e.id === id);
}

export function libraryPromptIndex(): string {
  const groups: Array<[string, CanonicalEffect['type']]> = [
    ['TRANSFORMS / MOTION', 'transform'],
    ['OVERLAYS', 'overlay'],
    ['TRANSITIONS', 'transition'],
    ['EFFECTS', 'effect'],
    ['COMPOUND RECIPES (prefer when 2+ layers)', 'compound'],
  ];
  return groups
    .map(([label, type]) => {
      const rows = EFFECT_LIBRARY.filter((e) => e.type === type)
        .map((e) => `${e.id} | ${e.canonicalName} aka ${e.aliases.join(', ')}`)
        .join('\n');
      return rows ? `### ${label}\n${rows}` : '';
    })
    .filter(Boolean)
    .join('\n\n');
}
