import type { CanonicalEffect } from './types';
import { nleRecipes, transformRecipes } from './recipes';

function fx(
  partial: Omit<CanonicalEffect, 'minVisualClues' | 'combinations'> & {
    minVisualClues?: number;
    combinations?: string[];
  }
): CanonicalEffect {
  return {
    minVisualClues: 3,
    combinations: [],
    ...partial,
  };
}

const overlay = (name: string, steps: string[]) =>
  nleRecipes({
    ae: { name, steps },
    premiere: { name, steps },
    capcut: { name, steps },
    davinci: { name, steps },
    vn: { name, steps },
  });

/** Overlays, extra camera/transforms, 3D, and compound recipes. */
export const EXTRA_LIBRARY: CanonicalEffect[] = [
  fx({
    id: 'OV_000306',
    canonicalName: 'Film Matte',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Frame',
    description: 'Hard film-gate crop / rounded matte around the picture.',
    visualSignatures: ['Hard frame edge', 'Rounded or square gate', 'Picture does not extend past the matte'],
    detectionKeywords: ['film matte', 'gate', 'rounded frame'],
    aliases: ['Gate matte', 'film frame'],
    parameters: [{ name: 'Feather', range: '0–12px' }],
    layerOrder: 'Above picture, below text',
    similarEffects: ['Letterbox / Black Bars', 'Frame Overlay'],
    softwareRecipes: overlay('Film matte overlay', [
      'Add a matte PNG or shape',
      'Scale to the 9:16 frame',
      'Keep it locked — it should not track the subject',
    ]),
  }),
  fx({
    id: 'OV_000307',
    canonicalName: 'CRT Lines',
    type: 'overlay',
    category: 'Screen',
    subcategory: 'CRT',
    description: 'Fine interlaced TV scan texture, denser than a few black bars.',
    visualSignatures: ['Fine repeating lines', 'Interlace shimmer', 'Full-frame texture'],
    detectionKeywords: ['crt lines', 'interlace', 'tv scan'],
    aliases: ['Interlace overlay', 'CRT scan'],
    parameters: [{ name: 'Opacity', range: '15–55%' }],
    layerOrder: 'Above grade, below text',
    similarEffects: ['Horizontal Scan Line / Black Bar Overlay', 'VHS / CRT Overlay'],
    softwareRecipes: overlay('CRT line overlay', [
      'Place a fine scanline texture',
      'Overlay or Soft Light at ~35%',
      'Scale to cover the frame',
    ]),
  }),
  fx({
    id: 'OV_000308',
    canonicalName: 'Grid Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Grid',
    description: 'HUD-style or rule-of-thirds grid over the picture.',
    visualSignatures: ['Regular grid lines', 'Does not warp the image', 'Usually low opacity'],
    detectionKeywords: ['grid overlay', 'rule of thirds', 'wireframe grid'],
    aliases: ['Wireframe grid', 'thirds grid'],
    parameters: [{ name: 'Opacity', range: '20–70%' }],
    layerOrder: 'Above picture',
    similarEffects: ['HUD Overlay', 'Frame Overlay'],
    softwareRecipes: overlay('Grid overlay', [
      'Add grid PNG or shape grid',
      'Full frame, Screen or Overlay blend',
      'Keep opacity low unless it is a HUD',
    ]),
  }),
  fx({
    id: 'OV_000309',
    canonicalName: 'HUD Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'HUD',
    description: 'Sci-fi / tracker HUD graphics: brackets, readouts, targeting.',
    visualSignatures: ['UI chrome on top of footage', 'Corners or targeting brackets', 'Often animated'],
    detectionKeywords: ['hud', 'targeting', 'sci-fi overlay', 'tracker ui'],
    aliases: ['Sci-fi HUD', 'targeting overlay'],
    parameters: [{ name: 'Opacity', range: '40–100%' }],
    layerOrder: 'Above picture, below captions',
    similarEffects: ['Grid Overlay', 'Frame Overlay'],
    softwareRecipes: overlay('HUD overlay', [
      'Place HUD graphic on a higher track',
      'Screen / Add if it is line art',
      'Keyframe any tracker motion',
    ]),
  }),
  fx({
    id: 'OV_000310',
    canonicalName: 'Frame Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Frame',
    description: 'Decorative border or Polaroid / film-frame graphic.',
    visualSignatures: ['Visible border around the shot', 'Static to the canvas', 'Picture inset'],
    detectionKeywords: ['frame overlay', 'border overlay', 'polaroid frame'],
    aliases: ['Border overlay', 'photo frame'],
    parameters: [{ name: 'Scale', range: 'fit to 9:16' }],
    layerOrder: 'Top of picture, below text',
    similarEffects: ['Film Matte', 'Letterbox / Black Bars'],
    softwareRecipes: overlay('Frame overlay', [
      'Place frame PNG',
      'Scale to canvas',
      'Keep the photo inside the opening',
    ]),
  }),
  fx({
    id: 'OV_000311',
    canonicalName: 'Rain Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Rain',
    description: 'Falling rain streaks composited over the shot.',
    visualSignatures: ['Diagonal or vertical streaks', 'Looping weather', 'Screen/Add blend'],
    detectionKeywords: ['rain overlay', 'rain streaks', 'weather rain'],
    aliases: ['Rain composite'],
    parameters: [{ name: 'Opacity', range: '30–90%' }],
    layerOrder: 'Above picture',
    similarEffects: ['Speed Lines', 'Fog Overlay'],
    softwareRecipes: overlay('Rain overlay', [
      'Drop looping rain footage',
      'Screen or Overlay blend',
      'Match falling direction to the shot',
    ]),
  }),
  fx({
    id: 'OV_000312',
    canonicalName: 'Smoke Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Smoke',
    description: 'Drifting smoke or haze plate.',
    visualSignatures: ['Soft volumetric wisps', 'Moves independently', 'Screen/Add'],
    detectionKeywords: ['smoke overlay', 'haze plate', 'cigarette smoke'],
    aliases: ['Haze overlay'],
    parameters: [{ name: 'Opacity', range: '20–80%' }],
    layerOrder: 'Above picture',
    similarEffects: ['Fog Overlay', 'Light Leak'],
    softwareRecipes: overlay('Smoke overlay', [
      'Place smoke plate',
      'Screen blend',
      'Slow time-remap if needed',
    ]),
  }),
  fx({
    id: 'OV_000313',
    canonicalName: 'Fog Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Fog',
    description: 'Low-lying or full-frame fog wash.',
    visualSignatures: ['Soft grey veil', 'Hides contrast in the distance', 'Slow drift'],
    detectionKeywords: ['fog overlay', 'mist', 'ground fog'],
    aliases: ['Mist overlay'],
    parameters: [{ name: 'Opacity', range: '15–70%' }],
    layerOrder: 'Above picture',
    similarEffects: ['Smoke Overlay', 'Film Grain'],
    softwareRecipes: overlay('Fog overlay', [
      'Fog plate or fractal noise',
      'Soft Light / Overlay',
      'Keep motion slow',
    ]),
  }),
  fx({
    id: 'OV_000314',
    canonicalName: 'Bokeh Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Bokeh',
    description: 'Out-of-focus light orbs composited on the frame.',
    visualSignatures: ['Soft circular highlights', 'Usually Screen blend', 'Foreground or edge'],
    detectionKeywords: ['bokeh overlay', 'bokeh orbs', 'circle highlights'],
    aliases: ['Bokeh lights'],
    parameters: [{ name: 'Opacity', range: '25–80%' }],
    layerOrder: 'Above picture',
    similarEffects: ['Lens Flare', 'Light Leak'],
    softwareRecipes: overlay('Bokeh overlay', [
      'Bokeh plate, Screen blend',
      'Scale / position to the light side',
      'Keyframe if the camera moves',
    ]),
  }),
  fx({
    id: 'OV_000315',
    canonicalName: 'VHS Overlay',
    type: 'overlay',
    category: 'Overlay',
    subcategory: 'Scanline',
    description: 'Tracking noise, date stamp, and analog dirt as a plate.',
    visualSignatures: ['Tracking bar', 'Timestamp in a corner', 'Soft analog warp'],
    detectionKeywords: ['vhs overlay', 'tracking bar', 'rec timestamp'],
    aliases: ['VHS plate', 'camcorder overlay'],
    parameters: [{ name: 'Opacity', range: '40–100%' }],
    layerOrder: 'Above grade',
    similarEffects: ['VHS / CRT Overlay', 'CRT Lines'],
    softwareRecipes: overlay('VHS overlay', [
      'VHS overlay clip',
      'Overlay or Lighten',
      'Trim to the look section',
    ]),
  }),
  fx({
    id: 'FX_000155',
    canonicalName: 'Wave / Ripple Distortion',
    type: 'effect',
    category: 'Distortion',
    subcategory: 'Wave',
    description: 'Sine or ripple warp through the image.',
    visualSignatures: ['Wavy edges', 'Liquid motion', 'Often on a transition'],
    detectionKeywords: ['wave warp', 'ripple', 'liquid distortion'],
    aliases: ['Ripple', 'liquid warp'],
    parameters: [
      { name: 'Amplitude', range: '2–40' },
      { name: 'Wavelength', range: '8–80' },
    ],
    layerOrder: 'On the clip',
    similarEffects: ['Glitch Tear Cut', 'RGB Split Glitch'],
    softwareRecipes: nleRecipes({
      ae: { name: 'Wave Warp', steps: ['Effect > Distort > Wave Warp', 'Keyframe height on the hit'] },
      premiere: { name: 'Wave Warp', steps: ['Effects > Distort > Wave Warp'] },
      capcut: { name: 'Wave', steps: ['Effects > Distortion / Wave'] },
      davinci: { name: 'Ripple', steps: ['OpenFX Wave / Ripple'] },
      vn: { name: 'Wave', steps: ['Add Wave / Distort'] },
    }),
  }),
  fx({
    id: 'FX_000221',
    canonicalName: '3D Camera Orbit',
    type: 'effect',
    category: '3D',
    subcategory: '3D',
    description: 'Parallax orbit as if the camera swung around a 3D subject.',
    visualSignatures: ['Subject parallax', 'Background slides opposite', 'Not a 2D scale-only zoom'],
    detectionKeywords: ['3d orbit', 'parallax', 'orbit camera', '3d camera'],
    aliases: ['Parallax orbit', '3D swing'],
    parameters: [
      { name: 'Orbit', range: '8–45°' },
      { name: 'Duration', range: '0.3–1.2s' },
    ],
    layerOrder: '3D camera / transform on the layer',
    similarEffects: ['Zoom In + Clockwise Rotation', 'Horizontal Camera Pan'],
    softwareRecipes: nleRecipes({
      ae: { name: '3D Camera / CC Cylinder', steps: ['Enable 3D layer', 'Orbit the camera', 'Motion blur on'] },
      premiere: { name: 'Transform + Crop', steps: ['Fake parallax with scale + position'] },
      capcut: { name: '3D / Keyframes', steps: ['3D effect or keyframe orbit'] },
      davinci: { name: 'Fusion 3D', steps: ['Fusion camera orbit'] },
      vn: { name: '3D', steps: ['3D transform if available'] },
    }),
  }),
  fx({
    id: 'MOTION_005',
    canonicalName: 'Horizontal Camera Pan',
    type: 'transform',
    category: 'Camera',
    subcategory: 'Pan',
    description: 'Lateral position move — not a zoom.',
    visualSignatures: ['Frame slides sideways', 'Subject tracks or exits', 'Often with directional blur'],
    detectionKeywords: ['camera pan', 'lateral pan', 'position x'],
    aliases: ['Track pan', 'slide pan'],
    parameters: [
      { name: 'Position X', range: 'offset in px' },
      { name: 'Duration', range: '0.2–0.8s' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Whip Pan Transition', 'Zoom In + Clockwise Rotation'],
    softwareRecipes: transformRecipes('Position X', 'Position', 'Position'),
  }),
  fx({
    id: 'MOTION_006',
    canonicalName: 'Zoom In + Counterclockwise Rotation',
    type: 'transform',
    category: 'Transform',
    subcategory: 'Zoom',
    description: 'Scale punch with negative Z rotation.',
    visualSignatures: ['Frame enlarges', 'Rotates the opposite way of clockwise', 'Often motion-blurred'],
    detectionKeywords: ['counterclockwise', 'counter-clockwise', 'anti-clockwise', 'negative rotation'],
    aliases: ['Zoom CCW', 'zoom -rotation'],
    parameters: [
      { name: 'Scale', range: '100% → 112–140%' },
      { name: 'Rotation', range: '0° → -6° to -15°' },
      { name: 'Duration', range: '0.25–0.6s' },
      { name: 'Motion Blur', range: 'On' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom In + Clockwise Rotation'],
    combinations: ['CMP_ZOOM_ROTATE', 'CMP_ZOOM_ROTATE_FLASH'],
    softwareRecipes: transformRecipes('Scale + Rotation', 'Scale + Rotation', 'Zoom + Angle'),
  }),
  fx({
    id: 'TR_000411',
    canonicalName: 'Zoom Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Zoom',
    description: 'Scale-through cut: outgoing punches in, incoming settles.',
    visualSignatures: ['Scale continues across the cut', 'Cut near peak scale', 'Incoming eases down'],
    detectionKeywords: ['zoom transition', 'scale through cut'],
    aliases: ['Punch-through cut'],
    parameters: [
      { name: 'Scale', range: '100% → 140%+' },
      { name: 'Duration', range: '0.2–0.5s' },
    ],
    layerOrder: 'Across the cut',
    similarEffects: ['Zoom Blur Transition', 'Zoom In + Clockwise Rotation'],
    softwareRecipes: transformRecipes('Scale', 'Scale', 'Zoom'),
  }),
  fx({
    id: 'TR_000412',
    canonicalName: 'Rotate Transition',
    type: 'transition',
    category: 'Transition',
    subcategory: 'Rotate',
    description: 'Small Z rotation through the cut, not a full spin.',
    visualSignatures: ['Few degrees of rotation across the edit', 'Often with scale', 'Settles on incoming'],
    detectionKeywords: ['rotate transition', 'tilt cut'],
    aliases: ['Tilt transition'],
    parameters: [{ name: 'Rotation', range: '6–25°' }],
    layerOrder: 'Across the cut',
    similarEffects: ['Spin Transition', 'Zoom In + Clockwise Rotation'],
    softwareRecipes: transformRecipes('Rotation', 'Rotation', 'Angle'),
  }),
  fx({
    id: 'CMP_ZOOM_ROTATE',
    canonicalName: 'Zoom + Rotation',
    type: 'compound',
    category: 'Transform',
    subcategory: 'Compound',
    description: 'Scale and Z-rotation together — never label this as only Zoom.',
    visualSignatures: ['Scale increases', 'Frame rotates a few degrees', 'Shared duration'],
    detectionKeywords: ['zoom rotate', 'zoom + rotation', 'scale and rotate'],
    aliases: ['Punch + rotate', 'scale rotation combo'],
    parameters: [
      { name: 'Scale', range: '100% → 112–145%' },
      { name: 'Rotation', range: '±6–15°' },
      { name: 'Duration', range: '0.28–0.55s' },
      { name: 'Easing', range: 'Ease Out + Overshoot' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom In + Clockwise Rotation', 'Zoom + Directional Blur'],
    combinations: [],
    softwareRecipes: transformRecipes('Scale + Rotation', 'Scale + Rotation', 'Zoom + Angle'),
  }),
  fx({
    id: 'CMP_FLASH_SHAKE',
    canonicalName: 'Flash + Impact Shake',
    type: 'compound',
    category: 'Lighting',
    subcategory: 'Compound',
    description: 'White flash stacked with a short camera hop.',
    visualSignatures: ['White peak', 'Frame hops', 'Same beat'],
    detectionKeywords: ['flash shake', 'hit flash', 'impact flash shake'],
    aliases: ['Hit flash', 'flash jitter'],
    parameters: [
      { name: 'Flash', range: '0% → 70% → 0%' },
      { name: 'Amplitude', range: '4–24px' },
    ],
    layerOrder: 'Flash overlay above shaken clip',
    similarEffects: ['Flash Frame', 'Impact Camera Shake'],
    combinations: ['FX_000180', 'MOTION_003'],
    softwareRecipes: nleRecipes({
      ae: {
        name: 'Flash + Position',
        steps: ['White flash 0–70–0', 'Position jitter 2–4 frames', 'Motion blur on'],
      },
      premiere: {
        name: 'Dip to White + Position',
        steps: ['Short Dip to White', 'Nudge position'],
      },
      capcut: {
        name: 'Flash + Shake',
        steps: ['Flash effect', 'Shake effect, short'],
      },
      davinci: {
        name: 'Flash + Position',
        steps: ['Gain spike', 'Inspector position jitter'],
      },
      vn: {
        name: 'Flash + Shake',
        steps: ['Flash', 'Shake'],
      },
    }),
  }),
  fx({
    id: 'CMP_ZOOM_SHAKE',
    canonicalName: 'Zoom + Shake',
    type: 'compound',
    category: 'Transform',
    subcategory: 'Compound',
    description: 'Punch-in that lands with handheld jitter.',
    visualSignatures: ['Scale up', 'Settle includes shake', 'On a hit'],
    detectionKeywords: ['zoom shake', 'punch shake'],
    aliases: ['Punch + shake'],
    parameters: [
      { name: 'Scale', range: '100% → 115–130%' },
      { name: 'Amplitude', range: '4–18px' },
    ],
    layerOrder: 'Transform on the base clip',
    similarEffects: ['Zoom In + Clockwise Rotation', 'Impact Camera Shake'],
    combinations: ['MOTION_001', 'MOTION_003'],
    softwareRecipes: transformRecipes('Scale + Position', 'Scale + Position', 'Zoom + Position'),
  }),
];
